import type { Metadata } from "next";
import "./globals.css";
import { Chakra_Provider } from "@/components/ui/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <Chakra_Provider>{children}</Chakra_Provider>
      </body>
    </html>
  );
}
